### PR TITLE
Added ability to display blueprint item composition in upload form

### PR DESCRIPTION
**Pull request by sho918**
Added ability to display blueprint item composition in upload form.
This allow check blueprint before upload, so probably useful.

In order to reference image files from Javascript, some images are now handled by Webpacker.
If there is any other good way to reference images from Javascript, please let me know.

<details>
<summary>Example image</summary>

- BP Data: https://www.dysonsphereblueprints.com/blueprints/1-universe-matrix-per-second-from-the-ore

localhost_3000_blueprints_new
</details>

### CODE REVIEW

**Comment by gabriel-dehan** [comment]
This looks really cool, thanks for the example image!

I'll have to change update the style a bit and find a way to make this take a bit less space but that's really great, thank you.
I'll merge it in the next few days :)

**Comment by gabriel-dehan** [comment]
Hey, sorry I haven't merged your PR yet, haven't forgotten it, just haven't had the time recently, was hoping I could merge it earlier.  But I'll be way more free from next week onward, so I'll be able to handle that then :)

**Comment by gabriel-dehan** [comment]
Deeply sorry for not merging before, had some personal issues I needed to take care of. Just merged your branch, I'll do some adjustments (mainly style wise) and then I'll push it live. Thanks a lot for your hardwork and support.

**Comment by sho918** [comment]
It's fine, thanks!

**Pull request merged**
