### PR TITLE
Add support for DSP blueprint parsing

### PR DESCRIPTION
**Pull request by LRFalk01**
Add blueprint parsing back for DSP based blueprints. This will only fill in when the blueprint is modified. We'd probably want to run something to backfill if summary is missing.

### CODE REVIEW

**Comment by gabriel-dehan** [comment]
Hey, seems like you manage to make the project work on your side, nice :) 

And thanks, I Just read the code quickly, seems good, I'll have to test out a few things and I was just thinking (right before I saw your PR, a nice coincidence ahah) about the background job that would handle the backfilling.

**Comment by LRFalk01** [comment]
We could simply check to see if the blueprint has been parsed in show, and if not try to parse it. This would spare the job to do it, at the expense of running the parse on load potentially. Albeit, once.

**Comment by LRFalk01** [comment]
I reverted my Ruby to 3.0.0 from 3.0.2 and did my best to make Gemfile.lock as clean as I could... It no longer runs for me on windows, but maybe it works for you. If it's also broken for you, I suppose the `bundle update` was needed.

**Comment by gabriel-dehan** [comment]
@LRFalk01 yeah we're not going to do it on the show page, I really don't like doing that I'll just whip up a rake task to do it, it'll take like 10 minutes or something :) 
I'll look into it today I should have the time

**Comment by LRFalk01** [comment]
Optional parse on show reverted.

**Comment by gabriel-dehan** [comment]
It's live, thanks for your hard work!

**Comment by LRFalk01** [comment]
Awesome. Glad it worked. I tried to make a Ruby port of DSP's MD5 alg and it's crazy slow. Going to see if someone can help me make a C port so I can call it from Ruby

**Comment by gabriel-dehan** [comment]
When you say you tried, you mean the gem you release right? Doesn't seem to be that slow at decoding the blueprint though?

**Comment by LRFalk01** [comment]
DSP is using a custom hashing algorithm to validate the blueprint string.
My port of that was very slow. If I can figure it out, it allows for a
fully functioning validate method as well as the ability to encode
blueprints programmatically.

**Comment by gabriel-dehan** [comment]
Yeah I figured it was a problem for encoding, that'd be amazing, especially since I plan to add some blueprint editor functionalities :)

**Comment by LRFalk01** [comment]
I was able to rewrite DSP's custom hashing method into c and call it from
my Ruby gem. Going to clean it up today, and push it to RubyGems. This will
add an is valid method to the gem which I believe will be true to the game.

**Pull request merged**
