### PR TITLE
Install rubocop and correct offences

### PR DESCRIPTION
**Pull request by sho918**
Install rubocop and correct offences.
Let me know if you don't like the code style.

### CODE REVIEW

**Comment by sho918** [comment]
Thanks for review.
I've changed and force-pushed.

**Comment by gabriel-dehan** [comment]
I tried your PR, it breaks. You definitely should not modify any of the core rails files, like the files in the `bin/` folder, etc... 
Please make sure to fix this and test your changes before updating your PR :pray:  Couldn't even get past the bundle install.

Thank you.

PS: I am in the process of release v.3.2.0 so some files have changed.

**Comment by sho918** [comment]
Sorry about that ;(
I usually use `bundle install` and `bundle exec rails xx` to execute commands, so I didn't realize that.

Excluded `bin/` from rubocop and rebase onto main branch.
Thank you for your time.

**Comment by sho918** [comment]
I think it's not ideal to require actual S3 services for development.
So, created docker-compose file to make it easier to build the development environment.
What do you think about it?

**Comment by gabriel-dehan** [comment]
Hey @sho918, sorry for the delay. I am not opposed to adding the option to use docker for development, it's amazing for the community and I thank you for that, it's really really cool! 
But I need it to be an option, I personally loathe docker, it's slow, bloated and always an immense pain. I use it at work when it is required but I don't want to have to use it for my own personal projects :D
I haven't yet checked out your branch to see how the changes to some config files would impact the development workflow without docker :) It might need some minor tweaks.

I am by no means a docker expert so I do have a few questions:
- Is it necessary to have the database be in the docker? I don't see it really being in the way of the development. 
- I am not sure how sidekiq interfaces with a dockerized redis without any configuration. Might be something you missed or something I am not understanding :) 

I am also wondering why you changed the SMTP options in the `config/environments/production.rb` file?

Thanks man.

**Comment by sho918** [comment]
Thanks for the reply.

> Is it necessary to have the database be in the docker? I don't see it really being in the way of the development.

Of course, this is not necessary if you are running the database locally.
Added middleware not listed in Procfile to docker-compose.

> I am not sure how sidekiq interfaces with a dockerized redis without any configuration.
> Might be something you missed or something I am not understanding :)

Connection settings for Redis and Sidekiq are described in `config/initializers/redis.rb`.
(https://github.com/gabriel-dehan/dyson-sphere-blueprints/pull/24/files#diff-6ca0601d8a8ae0e917f92947b7342346054078c985b15d2eddde59f551b2a91eR2)

Puma and Sidekiq were included in the Procfile, so I did not add them to docker-compose.
I assumed that to use Foreman etc to start puma and sidekiq.

> I am also wondering why you changed the SMTP options in the config/environments/production.rb file?

To separate the SMTP settings for the development and production environments, moved the settings to each environment file.

(I translated most of it with Deepl. I'm sorry if the text is strange.)

**Comment by gabriel-dehan** [comment]
(Damn, Deepl works very well, wouldn't be able to tell you weren't a native speaker!)

> If you do not use Docker for development, it should be fine if you do not start it.
> I don't know what your local database settings, but if set through environment variables, it will work without Docker.

By default rails uses the default user and password so you don't actually have to setup anything in your environment variables which is pretty convenient, I'll have to see if it works without touching anything with your changes to the database.yml config file when I am home from work :) 

> Connection settings for Redis and Sidekiq are described in config/initializers/redis.rb.

Oh yeah, totally forgot about that. Should work as is.

> To separate the SMTP settings for the development and production environments, moved the settings to each environment file.

Ah I see, I had forgotten that I started setting up sendgrid at some point and thought you added this yourself and was wondering where it came from.

**Comment by sho918** [comment]
Deepl and Google Translate are really great.

> By default rails uses the default user and password 

I didn't know about this. I always used `database.yml` to configure it.
It may not work as it is because I have changed the `database.yml` to read from environment variables.

Should I revert the changes and create a file (eg: `database.yml.sample`) for users who use Docker?

**Comment by gabriel-dehan** [comment]
It seems so, at least from and to Japanese I guess :p 

Hey, no need, I just tested it and it works fine because as long as you don't set the ENV variables they are considered nil, which makes rails use its defaults.

Just re-read every change and checked a bunch of things, everything seems to be working properly so I am going to merge it now. 
Some of the changes/fixes I read were actually quite instructive, some other just reminded me that I spent way too much time writing Javascript lately (so many `===` I wrote by mistake :p). Thanks for that.

**Comment by sho918** [comment]
Thanks!

**Pull request merged**
